"""Configuration for the placeholder 18-DOF hexapod.

The URDF is generated by ``scripts/generate_hexapod_urdf.py`` (placeholder for
the real model built in a separate project). It is spawned via
:class:`~isaaclab.sim.UrdfFileCfg`, which converts URDF -> USD on first load
and caches the result, so no manual conversion step is needed.

Actuator model — Dynamixel XM430-W350 class (12 V):

* stall torque 4.1 N*m  -> ``effort_limit_sim = 3.0`` N*m (sustained, derated)
* no-load speed 46 rpm  -> ``velocity_limit_sim = 4.8`` rad/s
* PD gains Kp = 25 N*m/rad, Kd = 0.5 N*m*s/rad — starting point sized for
  ~0.1-0.3 kg*m^2-scale leg inertias; expect to tune once M2 training starts.

Never leave actuators unbounded — unbounded actuators are how policies learn
physically impossible gaits.
"""

from pathlib import Path

import isaaclab.sim as sim_utils
from isaaclab.actuators import ImplicitActuatorCfg
from isaaclab.assets.articulation import ArticulationCfg

_URDF_PATH = str(Path(__file__).resolve().parents[4] / "assets" / "urdf" / "hexapod.urdf")

# XM430-class limits (see module docstring)
SERVO_EFFORT_LIMIT = 3.0  # N*m
SERVO_VELOCITY_LIMIT = 4.8  # rad/s
SERVO_STIFFNESS = 25.0  # N*m/rad
SERVO_DAMPING = 0.5  # N*m*s/rad

# Default standing pose — must match DEFAULT_JOINT_POSE in
# scripts/generate_hexapod_urdf.py. Foot sits ~0.10 m below the hip.
_DEFAULT_JOINT_POS = {
    ".*_coxa_joint": 0.0,
    ".*_femur_joint": -0.35,
    ".*_tibia_joint": 1.75,
}

HEXAPOD_CFG = ArticulationCfg(
    spawn=sim_utils.UrdfFileCfg(
        asset_path=_URDF_PATH,
        fix_base=False,
        activate_contact_sensors=True,
        joint_drive=sim_utils.UrdfFileCfg.JointDriveCfg(
            target_type="position",
            gains=sim_utils.UrdfFileCfg.JointDriveCfg.PDGainsCfg(
                stiffness=SERVO_STIFFNESS,
                damping=SERVO_DAMPING,
            ),
        ),
        rigid_props=sim_utils.RigidBodyPropertiesCfg(
            disable_gravity=False,
            retain_accelerations=False,
            linear_damping=0.0,
            angular_damping=0.0,
            max_linear_velocity=100.0,
            max_angular_velocity=100.0,
            max_depenetration_velocity=1.0,
        ),
        articulation_props=sim_utils.ArticulationRootPropertiesCfg(
            enabled_self_collisions=False,
            solver_position_iteration_count=4,
            solver_velocity_iteration_count=0,
        ),
    ),
    # Spawn at standing height (foot ~0.104 m below hip + foot radius). A drop
    # from higher up saturates the 3 N*m tibia drives on impact and the robot
    # cannot recover — realistic servos don't get back up from a belly-flop.
    init_state=ArticulationCfg.InitialStateCfg(
        pos=(0.0, 0.0, 0.12),
        joint_pos=_DEFAULT_JOINT_POS,
        joint_vel={".*": 0.0},
    ),
    soft_joint_pos_limit_factor=0.95,
    actuators={
        "legs": ImplicitActuatorCfg(
            joint_names_expr=[".*_coxa_joint", ".*_femur_joint", ".*_tibia_joint"],
            effort_limit_sim=SERVO_EFFORT_LIMIT,
            velocity_limit_sim=SERVO_VELOCITY_LIMIT,
            stiffness=SERVO_STIFFNESS,
            damping=SERVO_DAMPING,
        ),
    },
)
"""Placeholder hexapod articulation: 18 position-controlled joints, XM430-class limits."""
