"""Configuration for the spidertron-style 18-DOF hexapod.

The URDF is generated by the CAD pipeline — ``cd cad && uv run python
scripts/build_robot.py`` — from the parametric model in
``cad/src/hexapod_cad/``. Never edit the URDF; edit ``params.py`` and rerun.
Design rationale, torque sizing, and joint-limit verification:
``cad/DESIGN_LOG.md``.

Actuators — Feetech serial-bus servos at 12 V, modeled as ``DCMotor`` (hard
torque-speed envelope) with spec-sheet figures / 1.5 design factor on speed
and torque; joint range exact from the URDF:

* coxa yaw    : STS3215 — effort 1.96 N*m, velocity 4.78 rad/s
* femur/knee  : STS3250 — effort 3.27 N*m, velocity 5.25 rad/s
* PD gains Kp = 25 N*m/rad, Kd = 0.5 N*m*s/rad — carried over from the
  XM430-class starting point; expect to retune for the longer legs.

Sign conventions (match the URDF emitter, ``cad/src/hexapod_cad/params.py``):
femur pitch about +y with NEGATIVE = lift; knee positive = flexion.
Standing pose: coxa 0, femur -0.5236, tibia +1.8151 rad.
"""

from pathlib import Path

import isaaclab.sim as sim_utils
from isaaclab.actuators import DCMotorCfg
from isaaclab.assets.articulation import ArticulationCfg

_URDF_PATH = str(Path(__file__).resolve().parents[4] / "assets" / "urdf" / "spidertron.urdf")

# Feetech spec-sheet figures (cad/analysis/static_torque.py), hard-limited in
# sim via the DCMotor torque-speed model with a 1.5 DESIGN FACTOR on speed and
# torque/energy (joint RANGE stays exact from the URDF). The DCMotor model is
# the physical envelope the implicit drive lacked: torque saturates along the
# stall->no-load line, so beyond no-load speed the servo can only brake --
# which closes the solver energy-pumping exploit (march-free forensics: joints
# backdriven to 22.8 rad/s past the drive's velocity limit, KE 3.3x actuator
# work; velocity_limit_sim's PhysX clamp demonstrably leaks under contact).
#
# STS3215 (coxa):  stall 2.94 N*m, no-load 7.17 rad/s  -> /1.5: 1.96, 4.78
# STS3250 (pitch): stall 4.91 N*m, no-load 7.87 rad/s  -> /1.5: 3.27, 5.25
COXA_EFFORT_LIMIT = 1.96  # N*m  (STS3215 stall / 1.5)
COXA_VELOCITY_LIMIT = 4.78  # rad/s (no-load / 1.5)
PITCH_EFFORT_LIMIT = 3.27  # N*m  (STS3250 stall / 1.5)
PITCH_VELOCITY_LIMIT = 5.25  # rad/s (no-load / 1.5)
SERVO_STIFFNESS = 25.0  # N*m/rad
SERVO_DAMPING = 0.5  # N*m*s/rad

# Standing pose — must match HexapodParams.default_joint_pose_rad() in
# cad/src/hexapod_cad/params.py (femur -30 deg lift, knee 104 deg flexion).
_DEFAULT_JOINT_POS = {
    ".*_coxa_joint": 0.0,
    ".*_femur_joint": -0.5236,
    ".*_tibia_joint": 1.8151,
}

SPIDERTRON_CFG = ArticulationCfg(
    spawn=sim_utils.UrdfFileCfg(
        asset_path=_URDF_PATH,
        fix_base=False,
        activate_contact_sensors=True,
        joint_drive=sim_utils.UrdfFileCfg.JointDriveCfg(
            target_type="position",
            gains=sim_utils.UrdfFileCfg.JointDriveCfg.PDGainsCfg(
                stiffness=SERVO_STIFFNESS,
                damping=SERVO_DAMPING,
            ),
        ),
        rigid_props=sim_utils.RigidBodyPropertiesCfg(
            disable_gravity=False,
            retain_accelerations=False,
            linear_damping=0.0,
            angular_damping=0.0,
            max_linear_velocity=100.0,
            max_angular_velocity=100.0,
            max_depenetration_velocity=1.0,
        ),
        articulation_props=sim_utils.ArticulationRootPropertiesCfg(
            enabled_self_collisions=False,
            # 4 -> 8 position, 0 -> 1 velocity (march-free2 post-mortem):
            # velocity iterations materially improve friction convergence,
            # and brief high-speed foot taps need it
            solver_position_iteration_count=8,
            solver_velocity_iteration_count=1,
        ),
        # Contact integrity (march-free2 friction-evasion fix): at 4-6 m/s a
        # grazing 4 mm foot sphere touches for ~one 200 Hz step and TGS
        # friction anchors never engage -- measured tangential force was
        # exactly 0 on sliding loaded feet. The contact offset generates
        # contacts BEFORE touch so anchors exist by impact: 3 cm covers a
        # full 200 Hz step even at 6 m/s foot speed. Statics are unaffected
        # (rest_offset governs resting geometry; early contacts are
        # speculative and only apply force if the step would penetrate).
        # Revisit on M3 rough terrain: large offsets can graze near-miss
        # geometry. Torsional patch radius gives the point-like sphere a
        # finite friction patch.
        collision_props=sim_utils.CollisionPropertiesCfg(
            contact_offset=0.03,
            rest_offset=0.0,
            torsional_patch_radius=0.004,
        ),
    ),
    # Spawn at standing height: feet reach 0.2745 m below the base origin
    # (hip plane) at the standing pose. Same lesson as the placeholder —
    # dropping from height saturates the 3.4 N*m knees on impact.
    init_state=ArticulationCfg.InitialStateCfg(
        pos=(0.0, 0.0, 0.28),
        joint_pos=_DEFAULT_JOINT_POS,
        joint_vel={".*": 0.0},
    ),
    soft_joint_pos_limit_factor=0.95,
    actuators={
        "yaw": DCMotorCfg(
            joint_names_expr=[".*_coxa_joint"],
            saturation_effort=COXA_EFFORT_LIMIT,
            effort_limit=COXA_EFFORT_LIMIT,
            velocity_limit=COXA_VELOCITY_LIMIT,
            # keep the leaky-but-helpful PhysX clamp as a second fence
            velocity_limit_sim=COXA_VELOCITY_LIMIT,
            stiffness=SERVO_STIFFNESS,
            damping=SERVO_DAMPING,
        ),
        "pitch": DCMotorCfg(
            joint_names_expr=[".*_femur_joint", ".*_tibia_joint"],
            saturation_effort=PITCH_EFFORT_LIMIT,
            effort_limit=PITCH_EFFORT_LIMIT,
            velocity_limit=PITCH_VELOCITY_LIMIT,
            velocity_limit_sim=PITCH_VELOCITY_LIMIT,
            stiffness=SERVO_STIFFNESS,
            damping=SERVO_DAMPING,
        ),
    },
)
"""Spidertron hexapod articulation: 18 position-controlled joints, Feetech STS limits."""
