"""Configuration for the spidertron-style 18-DOF hexapod.

The URDF is generated by the CAD pipeline — ``cd cad && uv run python
scripts/build_robot.py`` — from the parametric model in
``cad/src/hexapod_cad/``. Never edit the URDF; edit ``params.py`` and rerun.
Design rationale, torque sizing, and joint-limit verification:
``cad/DESIGN_LOG.md``.

Actuators — Feetech serial-bus servos at 12 V, limits derated ~70% of stall
(see ``cad/analysis/static_torque.py``):

* coxa yaw    : STS3215 — effort 2.06 N*m, velocity 5.38 rad/s
* femur/knee  : STS3250 — effort 3.43 N*m, velocity 5.91 rad/s
* PD gains Kp = 25 N*m/rad, Kd = 0.5 N*m*s/rad — carried over from the
  XM430-class starting point; expect to retune for the longer legs.

Sign conventions (match the URDF emitter, ``cad/src/hexapod_cad/params.py``):
femur pitch about +y with NEGATIVE = lift; knee positive = flexion.
Standing pose: coxa 0, femur -0.5236, tibia +1.8151 rad.
"""

from pathlib import Path

import isaaclab.sim as sim_utils
from isaaclab.actuators import ImplicitActuatorCfg
from isaaclab.assets.articulation import ArticulationCfg

_URDF_PATH = str(Path(__file__).resolve().parents[4] / "assets" / "urdf" / "spidertron.urdf")

# Feetech limits, derated (cad/analysis/static_torque.py)
COXA_EFFORT_LIMIT = 2.06  # N*m  (STS3215, stall 2.94)
COXA_VELOCITY_LIMIT = 5.38  # rad/s
PITCH_EFFORT_LIMIT = 3.43  # N*m  (STS3250, stall 4.91)
PITCH_VELOCITY_LIMIT = 5.91  # rad/s
SERVO_STIFFNESS = 25.0  # N*m/rad
SERVO_DAMPING = 0.5  # N*m*s/rad

# Standing pose — must match HexapodParams.default_joint_pose_rad() in
# cad/src/hexapod_cad/params.py (femur -30 deg lift, knee 104 deg flexion).
_DEFAULT_JOINT_POS = {
    ".*_coxa_joint": 0.0,
    ".*_femur_joint": -0.5236,
    ".*_tibia_joint": 1.8151,
}

SPIDERTRON_CFG = ArticulationCfg(
    spawn=sim_utils.UrdfFileCfg(
        asset_path=_URDF_PATH,
        fix_base=False,
        activate_contact_sensors=True,
        joint_drive=sim_utils.UrdfFileCfg.JointDriveCfg(
            target_type="position",
            gains=sim_utils.UrdfFileCfg.JointDriveCfg.PDGainsCfg(
                stiffness=SERVO_STIFFNESS,
                damping=SERVO_DAMPING,
            ),
        ),
        rigid_props=sim_utils.RigidBodyPropertiesCfg(
            disable_gravity=False,
            retain_accelerations=False,
            linear_damping=0.0,
            angular_damping=0.0,
            max_linear_velocity=100.0,
            max_angular_velocity=100.0,
            max_depenetration_velocity=1.0,
        ),
        articulation_props=sim_utils.ArticulationRootPropertiesCfg(
            enabled_self_collisions=False,
            solver_position_iteration_count=4,
            solver_velocity_iteration_count=0,
        ),
    ),
    # Spawn at standing height: feet reach 0.2745 m below the base origin
    # (hip plane) at the standing pose. Same lesson as the placeholder —
    # dropping from height saturates the 3.4 N*m knees on impact.
    init_state=ArticulationCfg.InitialStateCfg(
        pos=(0.0, 0.0, 0.28),
        joint_pos=_DEFAULT_JOINT_POS,
        joint_vel={".*": 0.0},
    ),
    soft_joint_pos_limit_factor=0.95,
    actuators={
        "yaw": ImplicitActuatorCfg(
            joint_names_expr=[".*_coxa_joint"],
            effort_limit_sim=COXA_EFFORT_LIMIT,
            velocity_limit_sim=COXA_VELOCITY_LIMIT,
            stiffness=SERVO_STIFFNESS,
            damping=SERVO_DAMPING,
        ),
        "pitch": ImplicitActuatorCfg(
            joint_names_expr=[".*_femur_joint", ".*_tibia_joint"],
            effort_limit_sim=PITCH_EFFORT_LIMIT,
            velocity_limit_sim=PITCH_VELOCITY_LIMIT,
            stiffness=SERVO_STIFFNESS,
            damping=SERVO_DAMPING,
        ),
    },
)
"""Spidertron hexapod articulation: 18 position-controlled joints, Feetech STS limits."""
